import {
  AngularNodeAppEngine,
  createNodeRequestHandler,
  isMainModule,
  writeResponseToNodeResponse,
} from '@angular/ssr/node';
import express from 'express';
import { join } from 'node:path';

/**
 * Absolute path to the compiled browser distribution folder.
 *
 * This folder contains the built client-side assets (HTML, JS, CSS)
 * generated by Angular’s build process, located at `dist/browser`.
 */
const browserDistFolder = join(import.meta.dirname, '../browser');

/**
 * The Express application instance used as the web server.
 *
 * It serves static assets, handles REST API routes, and delegates
 * all other requests to Angular’s server-side rendering (SSR) engine.
 */
const app = express();

/**
 * The Angular server-side rendering (SSR) engine.
 *
 * This engine processes incoming requests and generates fully rendered
 * HTML responses based on the Angular application.
 *
 * @see {@link AngularNodeAppEngine}
 */
const angularApp = new AngularNodeAppEngine();

/**
 * Example Express Rest API endpoints can be defined here.
 * Uncomment and define endpoints as necessary.
 *
 * Example:
 * ```ts
 * app.get('/api/{*splat}', (req, res) => {
 *   // Handle API request
 * });
 * ```
 */

/**
 * Middleware to serve static files from the compiled `/browser` folder.
 *
 * This ensures Angular’s built assets (JS, CSS, images) are served efficiently.
 * The files are cached by the browser for up to one year (`maxAge: '1y'`).
 *
 * @remarks
 * - `index: false` prevents Express from automatically serving index.html.
 * - `redirect: false` disables directory redirects.
 */
app.use(
  express.static(browserDistFolder, {
    maxAge: '1y',
    index: false,
    redirect: false,
  }),
);

/**
 * Middleware to handle all non-static requests using Angular’s SSR engine.
 *
 * Delegates unmatched routes to the Angular application renderer, which
 * produces pre-rendered HTML responses or passes the request along if
 * no matching route is found.
 *
 * @param req The incoming HTTP request.
 * @param res The outgoing HTTP response.
 * @param next The next Express middleware function.
 */
app.use((req, res, next) => {
  angularApp
    .handle(req)
    .then((response) =>
      response ? writeResponseToNodeResponse(response, res) : next(),
    )
    .catch(next);
});

/**
 * Bootstraps and starts the Express server if this file is executed directly.
 *
 * When running in standalone mode (e.g., `node server.mjs`),
 * the server listens on the port specified by the `PORT` environment variable,
 * defaulting to `4000` if none is provided.
 *
 * @example
 * ```bash
 * PORT=8080 node server.mjs
 * ```
 */
if (isMainModule(import.meta.url)) {
  const port = process.env['PORT'] || 4000;
  app.listen(port, (error) => {
    if (error) {
      throw error;
    }

    console.log(`Node Express server listening on http://localhost:${port}`);
  });
}

/**
 * The Express request handler exported for use by external environments.
 *
 * This function allows the same Express app to be used by:
 * - Angular CLI dev-server (during `ng serve`)
 * - Serverless providers (e.g., Firebase Cloud Functions, Vercel)
 * - Custom Node or hosting environments
 *
 * @see {@link createNodeRequestHandler}
 */
export const reqHandler = createNodeRequestHandler(app);
